<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <link rel="shortcut icon" href="../img/t163.png"/>
<link rel="stylesheet" type="text/css" href="../css/style.css" media="screen"/>
<style>#emotion{margin:5px 0;}input:focus::-webkit-input-placeholder,textarea:focus::-webkit-input-placeholder{color:transparent;}::-webkit-scrollbar-track-piece{background:#FFF;}::-webkit-scrollbar{width:0px;height:8px;}::-webkit-scrollbar-thumb{height:50px;background-color:#999;border:none;}::-webkit-scrollbar-thumb:hover{background-color:#666;}.readmore{display:none}</style>
    <title>网易微博互粉管理工具</title>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
	<style>
		p {
			font-size:14px;
			}
	</style>
  </head>
  <body>
    <div class="notice" align="center" style="margin-top:10%;">
      <h1>网易微博互粉管理工具</h1>
	  <br/>
<p><img src="../img/t163.png" /><p>
<p>使用协议:作者保留一切解释权力！</p>
    <p><?php print_r($content); ?></p> 
	</div>
	<div class="success" align="center" style="position:fixed;bottom:-12px;width:100%;">Powered By <a title="天狼星の破晓" href="http://www.godwolfs.asia/">天狼星の破晓</a></div>
  </body>
</html>
